#!/usr/bin/env python
import sys

if sys.argv[1] == '-i':
    version = sys.stdin.read().strip()
else:
    version = sys.argv[1]

nums = version.split('.')
nums[-1] = str(int(nums[-1]) + 1)

print '.'.join(nums)
